name: ğŸ“˜ Update Docs

on:
  push:
    branches: [ "docs" ]

permissions: write-all

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: âš™ï¸ Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: âš™ï¸ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir

    - name: âš™ï¸ Setup git config
      run: |
        git config user.name "FernandoCelmer"
        git config user.email "email@fernandocelmer.com"

    - name: âš™ï¸ Commit report
      run: |
        echo "Commit Report" >> report.txt
        git add report.txt
        git commit -m "âš™ï¸ REPORT - Update"
        git push


